### Listar todas as contas
GET http://localhost:40000/getAllContasPagar
Content-Type: application/json

### Buscar uma conta por ID
POST http://localhost:40000/getContasPagarByID
Content-Type: application/json

{
  "id_contas": 2
}

### Buscar contas por usuário
POST http://localhost:40000/getContasPagarByUsuario
Content-Type: application/json

{
  "id_usuario": 1
}

### Criar uma nova conta
POST http://localhost:40000/insertContasPagar
Content-Type: application/json
  
 {
  "descricao": "Conta de agua",
  "valor": 250.75,
  "data_vencimento": "2025-10-25",
  "status": "Pendente",
  "id_usuario": 1
}



### Atualizar conta existente
POST http://localhost:40000/updateContasPagar
Content-Type: application/json

{
  "id_contas": 1,
  "descricao": "Conta de energia atualizada",
  "valor": 300.00,
  "data_vencimento": "2025-11-25",
  "status": "Pago"
}

### Deletar conta
POST http://localhost:40000/deleteContasPagar
Content-Type: application/json

{
  "id_contas": 1
}
