### Listar todos os usuários
GET http://localhost:40000/getAllUsuario
Content-Type: application/json

### Buscar um usuário por ID
POST http://localhost:40000/getUsuarioByID
Content-Type: application/json

{
  "id_user": 2
}

### Criar um novo usuário
POST http://localhost:40000/insertUsuario
Content-Type: application/json

{
  "nome": "Marcelo",
  "email": "Marcelo@example.com",
  "senha": "123456",
  "tipo": "PessoaFisica",
  "cpf_cnpj": "123.456.789-01"
}

### Atualizar usuário existente
POST http://localhost:40000/updateUsuario
Content-Type: application/json

{
  "id_user": 2,
  "nome": "Marcelo Atualizado",
  "email": "marcelo_novo@example.com",
  "senha": "654321",
  "tipo": "Empresa",
  "cpf_cnpj": "12.345.678/0001-99"
}

### Deletar usuário
POST http://localhost:40000/deleteUsuario
Content-Type: application/json

{
  "id_user": 2
}

### Login do usuário
POST http://localhost:40000/login
Content-Type: application/json

{
  "email": "mfavaro53@gmail.com",
  "senha": "123456"
}

### Logout do usuário
POST http://localhost:40000/logout
Content-Type: application/json